<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class uLoginRequest extends FormRequest
{
    /**
     * Determine if the users is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {

        return [
            'email' => 'required|min:6|max:32',
            'password' => 'required|min:6|max:32'
        ];
    }
    public function attributes()
    {
        return [
            'email'=> 'login/email'
        ]; // TODO: Change the autogenerated stub
    }
    public function messages()
    {
        return [
            'email.min'=> 'Email меньше положенного',
            'email.max'=> 'Email больше положенного',
            'email.required'=> 'Email - Пусто',
            'password.required'=> 'Email - Пусто'
        ]; // TODO: Change the autogenerated stub
    }
}
